apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: demo-backend
spec:
  template:
    metadata:
      name: demo-backend-v1
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: happycloudpak/knative-demo-backend
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_COLOR
          value: blue
        - name: APP_VERSION
          value: "v1.0"
